### ISSUE TITLE
ES6 ? 

### ISSUE THREAD

**Issue by cirocosta** [netshoes/styleguide#45]
Hi guys! 

Firstly, great work :+1: 

I was taking a look at the javascript part of the styleguide and didn't see any mentions to ES6. Are you using it at netshoes to some extent? Maybe not in prod? 

Thanks!

**Comment by rafaelrinaldi** [comment]
@cirocosta We are not using ES6 in production _yet_ :cry:

**Comment by cirocosta** [comment]
ooh  :weary: , are there too many reasons for not doing so (except maintaining existing codebases) nowadays? I mean, i've been away from working with js in production for some time, would like to know if this is still a hard issue

**Comment by rafaelrinaldi** [comment]
@cirocosta There are a few reasons:

1. Learning curve;
  * Not everyone on the team is comfortable with the new syntax yet.
2. No reliable way to programatically load modules yet (there's [`System`](https://github.com/systemjs/systemjs) which is stil a proposal);
  * A module system is not enough, we do a lot of conditional loading therefore the need for programatically load modules.
3. Legacy code;
  * The code base is ~5 years old. It's no easy task to simply upgrade everything to ES6 all of sudden.

On personal/fun projects we do use ES6, but using it in production is probably our least priority today.

**Comment by cirocosta** [comment]
hmm, that's fair, got it! Thanks for the complete answer! :+1:
