### ISSUE TITLE
Change the commit message standard

### ISSUE THREAD

**Issue by weslleyaraujo** [netshoes/styleguide#48]
Hey folks,

I'm open this issue for us to discuss our current [commit message standard](https://github.com/netshoes/styleguide/tree/master/scm#4.5).

At first I would like to make clear that I don't see any problem with our current pattern, is that I just found out that there is a know pattern followed by some projects and I think that would be awesome for us to start using the same way.

The new standard would follow the same idea with the "change type's" thing, but it is written in a different way like:

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

You can follow [this](https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md) explanation for each of those itens.

### Why's

* we would be following an already existing pattern created by many.
* we could generate CHANGELOG files using many existent [plugins](https://skywinder.github.io/github-changelog-generator/) which is awesome 😁
* sometimes it's nicer not to reinvent things

### Who already uses this

* [Semantic Release](https://github.com/semantic-release/semantic-release)
* [Angular JS](https://github.com/angular/angular/commits/master)
* [Spotify](https://www.youtube.com/watch?v=odZpA6yrOYY)

What you guys think of this idea?
(love you all 💜)

@netshoes/front-end

**Comment by raphaelfabeni** [comment]
I really liked the idea of generate changelogs. :heart: 
@weslleyaraujo Could you write some example of commit message?

**Comment by weslleyaraujo** [comment]
changelogs are awesome @raphaelfabeni 😅

lets say I have made a fix into our gulpfile:

```
fix(build): now gulp does some awesome logs

Closes #28
```

that small article above explains what each of that labels means..
its quite the same that we are used to 💪

**Comment by mauriciosoares** [comment]
I like it... it's basically the same thing as we already do... just changing a little bit the pattern.

And since integrates with a few other features, I don't see any reason why we would not use it.

+1 for this approach.

**Comment by rafaelrinaldi** [comment]
@weslleyaraujo I like it. Didn't knew there was a standard for this already. Let's just agree on what "change types" we are going to use (not sure if the ones we already use is enough) and then :shipit:

The idea of having a living changelog pleases me a lot. Just to keep in mind that this is something that we can only achieve after we start using tags for our (our = front-end as an isolated repository) code releases.

**Comment by raphaelfabeni** [comment]
@weslleyaraujo I see.
Just another doubt: everything in lowercase?

**Comment by weslleyaraujo** [comment]
@rafaelrinaldi thats true we could only start using the changelog thing (like for real)..
about the commit message I would propose:

| Prefix | Description |
|---|---|
| `feat` | When adding a feature that provides real value to the product |
| `fix` | When fixing a bug |
| `wip` | When testing something (work in progress) |
| `refactor` | When working on a refactor of some sort |
| `test ` | For non-changelog related tasks |

@raphaelfabeni we could use `Sentence case` and it be free to add long descriptions.. I just found out some examples from [this](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#) doc:

```
fix($compile): couple of unit tests for IE9

Older IEs serialize html uppercased, but IE9 does not...
Would be better to expect case insensitive, unfortunately jasmine does
not allow to user regexps for throw expectations.

Closes #392
Breaks foo.bar api, foo.baz should be used instead
```

The line with *Breaks*  will generate a block changing what this commit supposedly breaked..

**Comment by rafaelrinaldi** [comment]
The only thing is, if we're going to follow the standard, I think we should stick to its standards.
| Prefix | Description |
|---|---|
| `feat` | A new feature |
| `fix` | A bug fix |
| `docs` | Documentation only changes |
| `style` | Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc) |
| `refactor ` | A code change that neither fixes a bug or adds a feature |
| `test` | Adding missing tests |
| `chore` | Changes to the build process or auxiliary tools and libraries such as documentation generation |

Is that correct?

**Comment by mauriciosoares** [comment]
I think that's reasonable.

No problems from my side.

**Comment by raphaelfabeni** [comment]
:metal:

**Comment by philss** [comment]
Hey guys, there is a styleguide for change logs created by [Olivier Lacan](https://github.com/olivierlacan) that may help you.
It's called [Keep a CHANGELOG](http://keepachangelog.com/).

The goal of this style is to have only notable changes in chronological order (just like any other CHANGELOG),  separated by "change category" (I believe the `prefix` thing that you are suggesting).

The author talked about this at the [`#127` episode of the `Changelog Podcast`](https://changelog.com/127/).

I'm [using it](https://github.com/philss/floki/blob/master/CHANGELOG.md) and enjoying so far.

Hope it helps. :)

**Comment by rafaelrinaldi** [comment]
@philss Thanks Phil! I will look into that.

**Comment by philss** [comment]
@rafaelrinaldi :beers: :+1:
