### ISSUE TITLE
Broken link in styleguide/scm/readme

### ISSUE THREAD

**Issue by yvele** [netshoes/styleguide#52]
At [the end](https://github.com/netshoes/styleguide/blame/master/scm/README.md#L211) of the [scm/readme](https://github.com/netshoes/styleguide/blob/master/scm/README.md) file, the Conventional Changelog link is broken (404): https://github.com/ajoslin/conventional-changelog/blob/master/conventions/angular.md

Should it be replaced with: https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md ?

**Comment by raphaelfabeni** [comment]
Yeap!
Thanks! :metal:
